# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IniParserDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IniParserDemo
  pod 'DJIniParser', :path => '../'

  target 'IniParserDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IniParserDemoUITests' do
    # Pods for testing
  end

end
